
// This file is automatically generated by the Firebase setup.
// Do not edit this file manually.

import { FirebaseOptions } from 'firebase/app';

// =================================================================================
// TODO: INSERTA TU CONFIGURACIÓN DE FIREBASE AQUÍ
// Reemplaza este objeto con la configuración que copiaste desde la Consola de Firebase
// al registrar tu aplicación web.
// =================================================================================
const firebaseConfig: FirebaseOptions = {
  projectId: "turnolisto",
    appId: "1:938396553813:web:757277b538743177651a54",
      apiKey: "REDACTED",
        authDomain: "turnolisto.firebaseapp.com",
          storageBucket: "turnolisto.appspot.com",
            // Estos pueden estar vacíos, no son críticos para el emulador
              messagingSenderId: "938396553813",
                measurementId: "G-L9CVY813T8"
                };
                // =================================================================================
                // FIN DE LA SECCIÓN PARA EDITAR
                // =================================================================================


                /**
                 * The Firebase configuration object.
                  *
                   * This object is used to initialize the Firebase app. It is automatically
                    * generated by the Firebase setup and should not be edited manually.
                     *
                     * @see https://firebase.google.com/docs/web/setup#config-object
                      */
                      export function getFirebaseConfig(): FirebaseOptions {
                          if (!firebaseConfig.apiKey || firebaseConfig.apiKey.startsWith('TU_')) {
                                  throw new Error('La configuración de Firebase no está completa. Por favor, abre src/firebase/config.ts y pega la configuración de tu proyecto.');
                                      }
                                          return firebaseConfig;
                                          }
                                          
